# Generated by Django 2.1.2 on 2018-10-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181014_1156'),
        ('login', '0002_auto_20181011_1426'),
    ]

    operations = [
    ]
